### PR TITLE
Kafka not started but app running. Fixed #50

### LINKED ISSUE #50: Kafka not started but app running
```
2018-08-19 01:57:56.399 [main] WARN  carldata.cwilong.StatsD$ - Failed to lookup StatsD host
2018-08-19 01:57:57.009 [main] INFO  carldata.cwilong.Main$ - Application started
2018-08-19 01:58:01.657 [Cwilong-akka.actor.default-dispatcher-3] WARN  org.apache.kafka.clients.ClientUtils - Removing server prodkafka1:9092 from bootstrap.servers as DNS resolution failed for prodkafka1
2018-08-19 01:58:06.666 [Cwilong-akka.actor.default-dispatcher-3] WARN  org.apache.kafka.clients.ClientUtils - Removing server prodkafka2:9092 from bootstrap.servers as DNS resolution failed for prodkafka2
2018-08-19 01:58:11.673 [Cwilong-akka.actor.default-dispatcher-3] WARN  org.apache.kafka.clients.ClientUtils - Removing server prodkafka3:9092 from bootstrap.servers as DNS resolution failed for prodkafka3
[ERROR] [08/19/2018 01:58:11.692] [Cwilong-akka.actor.default-dispatcher-3] [akka://Cwilong/user/data-sink] Failed to construct kafka producer
akka.actor.ActorInitializationException: akka://Cwilong/user/data-sink: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:191)
	at akka.actor.ActorCell.create(ActorCell.scala:608)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:416)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:288)
	at carldata.cwilong.KafkaSink.<init>(KafkaSink.scala:24)
	at carldata.cwilong.Main$.$anonfun$main$1(Main.scala:46)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:563)
	at akka.actor.ActorCell.create(ActorCell.scala:589)
	... 9 more
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:373)
	... 16 more

2018-08-19 01:58:29.026 [Cwilong-akka.actor.default-dispatcher-8] WARN  carldata.cwilong.source.HttpActor - For http://dd.weather.gc.ca/model_gem_global/25km/grib2/lat_lon/00/030/CMC_glb_TMP_TGL_2_latlon.24x.24_#00_P030.grib2
Request failed, response code: 404 Not Found
2018-08-19 01:58:29.031 [Cwilong-akka.actor.default-dispatcher-4] WARN  carldata.cwilong.source.HttpActor - For http://dd.weather.gc.ca/model_gem_global/25km/grib2/lat_lon/00/231/CMC_glb_APCP_SFC_0_latlon.24x.24_#00_P231.grib2
Request failed, response code: 404 Not Found
```
We should handle error when kafka not found- log that and do not call weather services for data.

### PR DESCRIPTION
**Pull request by wenta**

### CODE REVIEW

File: src/main/scala/carldata/cwilong/KafkaSink.scala [hunk 1]
```diff
@@ -21,19 +22,27 @@ class KafkaSink(topic: String, brokers: String) extends Actor {
...
+    case _: KafkaException =>
+      logger.error("Failed to construct kafka producer.")
+      None
+    case _: Exception => None
+  }
 
   def receive: Actor.Receive = {
     case KMessage(k, vs) =>
-      vs.foreach { recVal =>
+      if (producer.isDefined) vs.foreach { recVal =>
```
Comment (klangner) [inline src/main/scala/carldata/cwilong/KafkaSink.scala]: you can use producer.forEach here
